- name: Upgrade Evaluator
  hosts: localhost
  vars: 
    filtered_pods: []
  tasks:
    - name: Read Pods List JSON file
      ansible.builtin.slurp:
        src: "{{ pods_json_file }}"
      register: pods_json

    - name: Parse JSON
      ansible.builtin.set_fact:
        pods_data: "{{ pods_json.content | b64decode | from_json }}"

    - name: PODS and Hosts Evaluator... (remove hosts with '103' - this will be based on vcenter tags!)
      ansible.builtin.set_fact:
        filtered_pods: "{{ filtered_pods + [filtered_pod] }}"
      vars:
        filtered_pod: >-
          {{
            pod | combine({
              'hosts': pod.hosts | select('search', '^(?!.*03$).*') | list
            })
          }}
      loop: "{{ pods_data }}"
      loop_control:
        loop_var: pod

    - name: Write Updated PODS JSON file
      ansible.builtin.copy:
        content: "{{ filtered_pods | to_json }}"
        dest: "{{ pods_json_file }}"
        mode: '0644'
