---
- name: Generate pod JSON for upgrade
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Define pod data
      ansible.builtin.set_fact:
        pod_data:
          - pod: "251"
            hosts:
              - "host1"
              - "host2"
              - "host3"
          - pod: "288"
            hosts:
              - "host100"
              - "host101"
              - "host102"
              - "host103"
              - "host104"
              - "host105"

    # - name: Write pod data to JSON file
    #   copy:
    #     content: '[{"pod":"251","hosts":["host1","host2","host3"]},{"pod":"288","hosts":["host100","host101","host102","host103","host104","host105"]}]'
    #     dest: /tmp/pods.json
    #     mode: '0644'

    - name: Write pod data to /tmp/pods.json
      ansible.builtin.copy:
        content: "'{{ pod_data | to_json | replace(' ', '') }}'"
        dest: /tmp/pods.json
        mode: '0644'

    - name: Debug the contents of pods.json
      ansible.builtin.debug:
        msg: "{{ lookup('file', '/tmp/pods.json') }}"
