---
- name: Generate pod JSON for upgrade
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Define pod data
      set_fact:
        pod_data:
          - pod: "251"
            hosts:
              - "host1"
              - "host2"
              - "host3"
          - pod: "288"
            hosts:
              - "host100"
              - "host101"
              - "host102"
              - "host103"
              - "host104"
              - "host105"

    - name: Write pod data to JSON file
      copy:
        content: "{{ pod_data | to_json | replace('\n', '') | replace(' ', '') }}"
        dest: /tmp/pods.json

    - name: Debug the content of pods.json
      run: cat /tmp/pods.json

    # - name: Debug the contents of pods.json
    #   debug:
    #     msg: "{{ lookup('file', '/tmp/pods.json') }}"
