# upgrade-playbook.yml

- name: Upgrade host
  hosts: localhost
  gather_facts: false
  vars:
    random_command: "bash -c 'echo $(( ( RANDOM % 3 ) + 1 ))'"
    min_minutes: 10 
    max_minutes: 20
  tasks:
    - name: Simulate upgrade
      ansible.builtin.debug:
        msg: "Upgrading {{ target_host }}"

    - name: Generate pause time between 1 and 5 minutes
      ansible.builtin.set_fact:
        pause_minutes: "{{ 1 + (min_minutes - max_minutes) | abs | random }}"

    - name: Show pause time
      ansible.builtin.debug:
        msg: "Pause time is {{ pause_minutes }} minutes"

    - name: Pause completing the upgrade
      ansible.builtin.pause:
        minutes: "{{ pause_minutes }}"
        # seconds: "{{ pause_minutes }}"

    - name: Generate random number between 1 and 3 using bash
      ansible.builtin.shell: "{{ random_command }}"
      register: random_result

    - name: Show the generated number
      ansible.builtin.debug:
        msg: "Generated number: {{ random_result.stdout }}"

    - name: Simulate failure if number is 1
      ansible.builtin.fail:
        msg: "Host Upgrade Failed!"
      when: random_result.stdout == "1"

    - name: Continue if no failure
      ansible.builtin.debug:
        msg: "Host Upgrade was Successful!"
