# upgrade-playbook.yml

- name: Upgrade host
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Simulate upgrade
      ansible.builtin.debug:
        msg: "Upgrading {{ target_host }}"

    - name: Generate pause time between 1 and 5 minutes
      ansible.builtin.set_fact:
        pause_minutes: "{{ 1 + (5 - 1) | random }}"

    - name: Pause completing the upgrade
      ansible.builtin.pause:
        # minutes: "{{ pause_minutes }}"
        seconds: "{{ pause_minutes }}"

    - name: Generate random number for failure simulation
      ansible.builtin.set_fact:
        failure_chance: "{{ 1 + (3 - 1) | random }}"

    - name: Simulate failure
      ansible.builtin.fail:
        msg: "Host Upgrade has failed!"
      when: failure_chance == 1

    - name: Simulate success
      ansible.builtin.debug:
        msg: "Host Upgrade has succeeded!"
      when: failure_chance != 1