# upgrade-playbook.yml

- name: Upgrade host
  hosts: localhost
  gather_facts: false
  vars:
    random_command: "bash -c 'echo $(( ( RANDOM % 3 ) + 1 ))'"
  tasks:
    - name: Simulate upgrade
      ansible.builtin.debug:
        msg: "Upgrading {{ target_host }}"

    - name: Generate pause time between 1 and 5 minutes
      ansible.builtin.set_fact:
        pause_minutes: "{{ 1 + (5 - 1) | random }}"

    - name: Pause completing the upgrade
      ansible.builtin.pause:
        # minutes: "{{ pause_minutes }}"
        seconds: "{{ pause_minutes }}"

    - name: Generate random number between 1 and 3 using bash
      shell: "{{ random_command }}"
      register: random_result

    - name: Show the generated number
      debug:
        msg: "Generated number: {{ random_result.stdout }}"

    - name: Simulate failure if number is 1
      fail:
        msg: "Simulated failure occurred! Random number was {{ random_result.stdout }}"
      when: random_result.stdout == "1"

    - name: Continue if no failure
      debug:
        msg: "No failure occurred. Playbook continues."