# .github/workflows/dynamic-hosts.yml
name: Dynamic Hosts Runner

on:
  repository_dispatch:
    types: [run-dynamic-hosts]

jobs:
  run-groups:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include: ${{ fromJson(github.event.client_payload.matrix) }}

    name: Run for ${{ matrix.id }}
    steps:
      - name: Process hosts
        run: |
          echo "Processing ID: ${{ matrix.id }}"
          for host in ${{ join(matrix.hosts, ' ') }}; do
            echo "Processing host: $host"
            sleep 1
          done
