# .github/workflows/main.yml
name: Dynamic ID and Hosts Runner

on:
  workflow_dispatch:
    inputs:
      config_json:
        description: 'JSON config like [{"id":"group1","hosts":["host1","host2"]}]'
        required: true

jobs:
  generate-and-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Save input matrix to file
        run: |
          echo '${{ github.event.inputs.config_json }}' > matrix.json

      - name: Dispatch child workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: run-dynamic-hosts
          client-payload: |
            {
              "matrix": ${{ github.event.inputs.config_json }}
            }
