name: Main Upgrade Workflow

on:
  workflow_dispatch:
    inputs:
      site:
        description: 'Site to process'
        required: true
        type: string
      start_time:
        description: 'Start of allowed time window (UTC HH:MM)'
        required: true
        default: '10:30'
      end_time:
        description: 'End of allowed time window (UTC HH:MM)'
        required: true
        default: '11:30'

jobs:
  get-pods:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Get pods (mock)
        id: set-matrix
        run: |
          # Replace this mock logic with your real pod/host generator
          POD_JSON='[{"pod":"251","hosts":["host1","host2"]}]'
          echo "matrix=$POD_JSON" >> $GITHUB_OUTPUT

  run-pods:
    needs: get-pods
    strategy:
      matrix:
        include: ${{ fromJson(needs.get-pods.outputs.matrix) }}
    uses: ./.github/workflows/handle-pod.yml
    with:
      pod: ${{ matrix.pod }}
      hosts: ${{ toJson(matrix.hosts) }}
      start_time: ${{ inputs.start_time }}
      end_time: ${{ inputs.end_time }}
