name: Upgrade POD
run-name: Upgrade POD - ${{ inputs.pod }} - ${{ github.run_id }}

permissions:
  actions: write
  contents: read

on:
  workflow_call:
    inputs:
      runname:
        required: true
        type: string
      pod:
        required: true
        type: string
      hosts:
        required: true
        type: string
      start_time:
        required: true
        type: string
      end_time:
        required: true
        type: string

  workflow_dispatch:
    inputs:
      runname:
        description: 'Run name for the workflow'
        required: true
        type: string
        default: 'Upgrade POD'
      pod:
        description: 'Pod to upgrade'
        required: true
        type: string
      hosts:
        description: 'Hosts for the pod'
        required: true
        type: string
      start_time:
        description: 'Start of allowed time window (Stockholm/CET HH:MM)'
        required: true
        type: string
      end_time:
        description: 'End of allowed time window (Stockholm/CET HH:MM)'
        required: true
        type: string
        
jobs:
  debug-hosts: 
    runs-on: ubuntu-latest
    name: Debug matrix hosts
    steps:
      - name: Debug Hosts
        run: |
          echo "THIS IS A TEST.... POD = ${{ inputs.pod }}, Hosts = ${{ inputs.hosts }}"

 