name: Parallel IDs with Serial Hosts

on:
  workflow_dispatch:

jobs:
  run-per-id:
    strategy:
      matrix:
        include:
          - id: group1
            hosts: "host1,host2"
          - id: group2
            hosts: "host3,host4"

    runs-on: ubuntu-latest
    name: Process ${{ matrix.id }}

    steps:
      - name: Split and Process Hosts Serially
        run: |
          IFS=',' read -ra HOSTS <<< "${{ matrix.hosts }}"
          for host in "${HOSTS[@]}"; do
            echo "Processing host: $host"
            # Simulate some work
            sleep 2
          done
