name: Parallel IDs with Serial Hosts

on:
  workflow_dispatch:

jobs:
  run-per-id:
    strategy:
      matrix:
        include:
          - id: pod_001
            hosts: "g1-host1,g1-host2,g1-host3,g1-host4"
          - id: pod_002
            hosts: "host3,host4"

    runs-on: ubuntu-latest
    name: Process ${{ matrix.id }}

    steps:
      - name: Split and Process Hosts Serially
        run: |
          IFS=',' read -ra HOSTS <<< "${{ matrix.hosts }}"
          for host in "${HOSTS[@]}"; do
            echo "Processing host: $host"
            # Simulate some work
            sleep 10
          done
